src/Entity/Jour.php
<?php

namespace App\Entity;

use App\Repository\JourRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=JourRepository::class)
 */
class Jour
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Num;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomClient;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Total;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $TotalTraite;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Reste;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getNum(): ?string
    {
        return $this->Num;
    }

    public function setNum(?string $Num): self
    {
        $this->Num = $Num;

        return $this;
    }

    public function getNomClient(): ?string
    {
        return $this->NomClient;
    }

    public function setNomClient(string $NomClient): self
    {
        $this->NomClient = $NomClient;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->Total;
    }

    public function setTotal(?int $Total): self
    {
        $this->Total = $Total;

        return $this;
    }

    public function getTotalTraite(): ?int
    {
        return $this->TotalTraite;
    }

    public function setTotalTraite(?int $TotalTraite): self
    {
        $this->TotalTraite = $TotalTraite;

        return $this;
    }

    public function getReste(): ?int
    {
        return $this->Reste;
    }

    public function setReste(?int $Reste): self
    {
        $this->Reste = $Reste;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $Matricule;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }

    public function setMatricule(string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->Matricule;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('password',RepeatedType::class, [
                'type'=>PasswordType::class,
                'first_options'=>['label'=>'Password'],
                'second_options'=>['label'=>'Confirm Password']
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    /**
     * @Route("/user", name="app_user")
     */
    public function index(): Response
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }

    /**
     * @Route("/contact", name="app_contact")
     */
    public function Contact(): Response
    {
        return $this->render('user/contact.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }


    /**
     * @Route("/profile", name="app_profile")
     */
    public function ResetPassword(): Response
    {
        return $this->render('user/profile.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }

//    /**
//     * @param Request $request
//     * @param $dateshm
//     * @param EntityManagerInterface $em
//     * @return Response
//     * @Route("/calendar/{dateshm}", name="datedesuivies")
//
//     */
//    public function suivie(Request $request , $dateshm ,EntityManagerInterface $em): Response
//
//    {
//        $em = $this->getDoctrine()->getManager();
//        $query6 = "
//                      SELECT
//                      *
//                      FROM jour
//                      where date = '".$dateshm."'
//                      ";
//
//        $stmt6 =  $em->getConnection()->prepare($query6);
//        $stmt6 ->execute();
//        $Jour = $stmt6->fetchAll();
//
//        return $this->render('user/calendar2.html.twig', [
//            'Jour'=>$Jour,
//        ]);
//
//    }



}

templates/user/calendar2.html.twig
{% extends 'base1.html.twig' %}

{% block sidebar %}
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link " href="{{ path('app_user') }}">
                    <i class="bi bi-grid"></i>
                    <span>Calendrier</span>
                </a>
            </li><!-- End Dashboard Nav -->

            <li class="nav-item">

                <a class="nav-link collapsed" href="{{path('app_profile')  }}">
                    <i class="bi bi-person"></i>
                    <span>Profile</span>
                </a>
            </li><!-- End Profile Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="{{path('app_contact')  }}">
                    <i class="bi bi-envelope"></i>
                    <span>Contact</span>
                </a>
            </li><!-- End Contact Page Nav -->


            {% if app.user %}
                <li class="nav-item">
                    <a class="nav-link collapsed" href="{{path('app_logout')  }}">
                        <i class="bi bi-box-arrow-in-right"></i>
                        <span>Déconnexion</span>
                    </a>
                </li><!-- End Login Page Nav -->
            {% endif %}
        </ul>
    </aside><!-- End Sidebar-->
{% endblock %}


{% block body %}
    <section id="container" style="margin-left: 22rem; margin-top: 7rem;">
        <section class="container" >
            <div class="row" style="display: flex;align-items: center;justify-content: center;margin-top: 120px;">

                <div class="col-lg-9">

                    <div class="card">
                        <div class="card-body" style="margin-top: 1rem;">

                            <!-- Table with stripped rows -->
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th >Date</th>
                                    <th>Id</th>
                                    <th> Nom de client </th>
                                    <th>Total à traité</th>
                                    <th>Total traité</th>
                                    <th>Reste</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for Jour in Jour %}
                                    <tr>
                                        <td>{{ Jour.date|date('d-m-Y') }}</td>
                                        <td>{{ Jour.num }}</td>
                                        <td><a href="#">{{ Jour.nom_client }}</a></td>
                                        <td>{{ Jour.total }}</td>
                                        <td>{{Jour.total_traite }}</td>
                                        <td>{{Jour.reste }}</td>
                                    </tr>

                                {% endfor %}

                                </tbody>
                            </table>
                            <!-- End small tables -->

                        </div>
                    </div>

                </div>



            </div>
        </section>

    </section>
{% endblock %}
{% block footer %}

{% endblock %}

templates/user/contact.html.twig
{% extends 'base1.html.twig' %}
{% block sidebar %}
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link " href="{{ path('app_user') }}">
                    <i class="bi bi-grid"></i>
                    <span>Calendrier</span>
                </a>
            </li><!-- End Dashboard Nav -->

            <li class="nav-item">

                <a class="nav-link collapsed" href="{{path('app_profile')  }}">
                    <i class="bi bi-person"></i>
                    <span>Profile</span>
                </a>
            </li><!-- End Profile Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="{{path('app_contact')  }}">
                    <i class="bi bi-envelope"></i>
                    <span>Contact</span>
                </a>
            </li><!-- End Contact Page Nav -->


            {% if app.user %}
                <li class="nav-item">
                    <a class="nav-link collapsed" href="{{path('app_logout')  }}">
                        <i class="bi bi-box-arrow-in-right"></i>
                        <span>Déconnexion</span>
                    </a>
                </li><!-- End Login Page Nav -->
            {% endif %}
        </ul>
    </aside><!-- End Sidebar-->
{% endblock %}

{% block body %}
    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Contact</h1>

        </div><!-- End Page Title -->

        <section class="section contact">

            <div class="row gy-4">

                <div class="col-xl-6">

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="info-box card">
                                <i class="bi bi-geo-alt"></i>
                                <h3>Addresse</h3>
                                <p>49 Rue des Entrepreneurs</p>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="info-box card">
                                <i class="bi bi-telephone"></i>
                                <h3>Appelez-nous</h3>
                                <p >71941535</p>
                            </div>
                        </div>
{#                        <div class="col-lg-6">#}
{#                            <div class="info-box card">#}
{#                                <i class="bi bi-envelope"></i>#}
{#                                <h3>Email Us</h3>#}
{#                                <p>info@example.com<br>contact@example.com</p>#}
{#                            </div>#}
{#                        </div>#}
                        <div class="col-lg-6">
                            <div class="info-box card">
                                <i class="bi bi-clock"></i>
                                <h3>Heures d'ouverture</h3>
                                <p>Lundi - Vendredi<br>08:00 - 16:30</p>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-xl-6">
                    <div class="card p-4">
                        <form action="forms/contact.php" method="post" class="php-email-form">
                            <div class="row gy-4">

                                <div class="col-md-6">
                                    <input type="text" name="name" class="form-control" placeholder="Nom" required>
                                </div>

                                <div class="col-md-6 ">
                                    <input type="email" class="form-control" name="email" placeholder=" Email" required>
                                </div>

                                <div class="col-md-12">
                                    <input type="text" class="form-control" name="subject" placeholder="Sujet" required>
                                </div>

                                <div class="col-md-12">
                                    <textarea class="form-control" name="message" rows="6" placeholder="Message" required></textarea>
                                </div>

                                <div class="col-md-12 text-center">
                                    <div class="loading">Loading</div>
                                    <div class="error-message"></div>
                                    <div class="sent-message">Votre message a été envoyé. Merci!</div>

                                    <button type="submit">Envoyer Le Message</button>
                                </div>

                            </div>
                        </form>
                    </div>

                </div>

            </div>

        </section>

    </main><!-- End #main -->
{% endblock %}
{% block footer %}
{% endblock %}

templates/user/index.html.twig
{% extends 'base1.html.twig' %}

 {% block sidebar %}
     <!-- ======= Sidebar ======= -->
     <aside id="sidebar" class="sidebar">

         <ul class="sidebar-nav" id="sidebar-nav">

             <li class="nav-item">
                 <a class="nav-link " href="{{ path('app_user') }}">
                     <i class="bi bi-grid"></i>
                     <span>Calendrier</span>
                 </a>
             </li><!-- End Dashboard Nav -->
             <li class="nav-item">

                 <a class="nav-link collapsed" href="{{path('app_profile')  }}">
                     <i class="bi bi-person"></i>
                     <span>Profile</span>
                 </a>
             </li><!-- End Profile Page Nav -->


             <li class="nav-item">
                 <a class="nav-link collapsed" href="{{path('app_contact')  }}">
                     <i class="bi bi-envelope"></i>
                     <span>Contact</span>
                 </a>
             </li><!-- End Contact Page Nav -->


             {% if app.user %}
                 <li class="nav-item">
                     <a class="nav-link collapsed" href="{{path('app_logout')  }}">
                         <i class="bi bi-box-arrow-in-right"></i>
                         <span>Déconnexion</span>
                     </a>
                 </li><!-- End Login Page Nav -->
             {% endif %}

         </ul>

     </aside><!-- End Sidebar-->
 {% endblock %}
{% block body %}

    <section style="margin-top: 7rem">
        <span id='loading'></span>

        <div id='calendar'>

        </div>
    </section>
    <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>

    <script>
        $(document).ready(function() {

            $( ".fc-daygrid-day" ).click(function() {
                //var date = $(this).attr('date-date') ;
                //console.log(calendar.formatIso(arg.start));
            });
        });
    </script>
{% endblock %}

{% block footer %}
{% endblock %}

templates/user/profile.html.twig
{% extends 'base1.html.twig' %}
{% block sidebar %}
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link " href="{{ path('app_user') }}">
                    <i class="bi bi-grid"></i>
                    <span>Calendrier</span>
                </a>
            </li><!-- End Dashboard Nav -->

            <li class="nav-item">

                <a class="nav-link collapsed" href="{{path('app_profile')  }}">
                    <i class="bi bi-person"></i>
                    <span>Profile</span>
                </a>
            </li><!-- End Profile Page Nav -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="{{path('app_contact')  }}">
                    <i class="bi bi-envelope"></i>
                    <span>Contact</span>
                </a>
            </li><!-- End Contact Page Nav -->


            {% if app.user %}
                <li class="nav-item">
                    <a class="nav-link collapsed" href="{{path('app_logout')  }}">
                        <i class="bi bi-box-arrow-in-right"></i>
                        <span>Déconnexion</span>
                    </a>
                </li><!-- End Login Page Nav -->
            {% endif %}
        </ul>
    </aside><!-- End Sidebar-->
{% endblock %}

{% block body %}
    <main id="main" class="main">


        <section class="section profile">
            <div class="row">


                <div class="col-xl-8">

                    <div class="card">
                        <div class="card-body pt-3">
                            <!-- Bordered Tabs -->
                            <ul class="nav nav-tabs nav-tabs-bordered">

                                <li class="nav-item">
                                    <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Changer mot de passe </button>
                                </li>

                            </ul>
                            <div class="tab-content pt-2">

                                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                                    <!-- Change Password Form -->
                                    <form>

                                        <div class="row mb-3">
                                            <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Mot de passe actuel</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input name="password" type="password" class="form-control" id="currentPassword">
                                            </div>
                                        </div>

                                        <div class="row mb-3">
                                            <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">Nouvelle mot de passe </label>
                                            <div class="col-md-8 col-lg-9">
                                                <input name="newpassword" type="password" class="form-control" id="newPassword">
                                            </div>
                                        </div>

                                        <div class="row mb-3">
                                            <label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Repeter mot de passe</label>
                                            <div class="col-md-8 col-lg-9">
                                                <input name="renewpassword" type="password" class="form-control" id="renewPassword">
                                            </div>
                                        </div>

                                        <div class="text-center">
                                            <button type="submit" class="btn btn-primary">Changer mot de passe</button>
                                        </div>
                                    </form><!-- End Change Password Form -->

                                </div>



                            </div><!-- End Bordered Tabs -->

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->
{% endblock %}
{% block footer %}
{% endblock %}